name: 'pr verify'

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
env:
  PR_NUMBER: pr${{ github.event.number }}
  PR_HASH: {{ github.event.pull_request.head.sha }}
jobs:
  build-msvc:
    name: 'test build (windows, msvc)'
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: PowerShell
        shell: pwsh
        run: .\test.ps1
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: yuzu-msvc-${{ env.BUILD_TAG }}
          path: artifacts/