name: 'pr verify'

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
env:
  PR_NUMBER: pr${{ github.event.number }}
jobs:
  build-msvc:
    name: 'test build (windows, msvc)'
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Inline Shell
        shell: pwsh
        run: |
        mkdir build
        cmake . -B build -DCMAKE_TOOLCHAIN_FILE="CMakeModules/MSVCCache.cmake" \
        -DUSE_CCACHE=ON -DYUZU_USE_BUNDLED_QT=1 -DYUZU_USE_BUNDLED_SDL2=1 \
        -DYUZU_USE_QT_WEB_ENGINE=ON -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON \
        -DYUZU_ENABLE_COMPATIBILITY_REPORTING=ON -DUSE_DISCORD_PRESENCE=ON \
        -DENABLE_QT_TRANSLATION=ON \
        -DCMAKE_BUILD_TYPE=Release -DGIT_BRANCH=pr-verify \
        -DCLANG_FORMAT_SUFFIX=discordplzdontclang
        ls build
        echo "how far will this work, anyways?"
      - name: PowerShell
        shell: pwsh
        run: .\test.ps1
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: yuzu-msvc-${{ env.BUILD_TAG }}
          path: artifacts/